export default async function handler(req, res) {
  try {
    const response = await fetch("https://blogs.rana.net.in/sitemap.xml");

    let xml = await response.text();

    xml = `<!-- Generated by FRONTEND API -->\n${xml}`;

    res.setHeader("Content-Type", "application/xml");
    res.status(200).send(xml);
  } catch (err) {
    res.status(500).send("Error");
  }
}